homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Enable Tracker device
device_tracker: !include tracker.yaml

# Weather prediction
#sensor:
#  - platform: yr

# Text to speech
tts:
  - platform: google
    language: it
    cache: true
    cache_dir: /tmp/tts

# Cloud
cloud:

group: !include groups.yaml
#automation: !include automations.yaml
automation: !include automation.yaml
script: !include scripts.yaml
#script: !include_dir_named script

sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
#camera: !include camera.yaml
switch: !include switch.yaml
climate: !include climate.yaml
input_number: !include input_number.yaml
light: !include light.yaml
media_player: !include cast.yaml
#media_player:
#  - platform: vlc
#    name: speaker_1
#    arguments: '--alsa-audio-device=hw:0,0'
google_assistant: !include assistant.yaml
zone: !include_dir_merge_list zones
panel_iframe:
    ingresso:
        title: 'Ingresso'
        url: 'http://192.168.3.160:8081'
        icon: mdi:webcam
    terminal:
        title: Terminal
        icon: mdi:console
        url: !secret terminal_url
shell_command:
    set_command_reboot: 'hassio host reboot'
