homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 0
  unit_system: metric
  time_zone: Europe/Rome
frontend:
config:
http:
  api_password: !secret http_password
updater:
#discovery:
#conversation:
#history:
#logbook:
sun:
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
switch: !include switch.yaml
climate: !include climate.yaml
input_number: !include input_number.yaml
automation: !include automation.yaml
#notify:
#  platform: telegram
#  api_key: 351197741:AAF5rEr8oJgzygt_8lMvLLQzsnh-EKO7rRQ
#  chat_id: Sharpec_bot
#automation:
#  - alias: Turn on kitchen light when there is movement
#    trigger:
#      platform: state
#      entity_id: binary_sensor.radio
#      to: 'on'
#    action:
#      service: switch.turn_on
#      entity_id: switch.sala
#      #data:
#      #  flash: long
#  - alias: Turn off kitchen light 10 minutes after last movement
#    trigger:
#      platform: state
#      entity_id: binary_sensor.radio
##      to: 'off'
#      for:
#        seconds: 10
#        #minutes: 1
#    action:
#      service: switch.turn_off
#      entity_id: switch.sala
#
#panel_iframe:
#  webcam:
#    title: 'WebCam'
#    icon: mdi:camera-iris
#    url: 'http://admin:YWRtaW4=@192.168.3.80:8080/stream/video/mjpeg'
#
#google_assistant:
#  project_id: homeassistant-186801
#  client_id: 38115967450-n747h466spcqndfo94gppjlme0m47vsb.apps.googleusercontent.com
#  access_token: TPIN_MzP4NdH3cbxqfMFykQ-
#  agent_user_id: [a string to identify user]
#  api_key: [an API Key generated for the Google Actions project]
#  exposed_domains:
#    - switch
#    - light
#    - group
